//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NvtecUploadFiles.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class arquivos
    {

        public int IdArquivo { get; set; }
        public string NomeArquivo { get; set; }
        public string ContentType { get; set; }
        public byte Visualizado { get; set; }
        public int IdDepartamento { get; set; }
        public int IdTipoDoc { get; set; }
        public int IdUsuarioRemetente { get; set; }
        public int IdUsuarioDestinatario { get; set; }
        public System.DateTime DataUpload { get; set; }
        public byte[] arquivo { get; set; }
        public string Descricao { get; set; }
        public Nullable<System.DateTime> DataUltDownload { get; set; }
        public int ContDownloads { get; set; }
    
        public virtual Departamento Departamento { get; set; }
        public virtual TipoDocumento TipoDocumento { get; set; }
        public virtual usuarios usuarios { get; set; }
        public virtual usuarios usuarios1 { get; set; }
    }
}
